### ISSUE TITLE
Usage details

### ISSUE THREAD

**Issue by 0323pin** [jperkin/mktool#2]
Hi,

First of all, thank you for this tool.
This is not really an issue, rather an usage question. The README states, that one should add `TOOLS_PLATFORM.mktool=  ${HOME}/.cargo/bin/mktool` to the existing `/etc/mk.conf`. Although, it doesn't say what to do if the following line already exists, `PKGSRC_USE_MKTOOLS= yes`?

I'd like to start using this tool instead of `pkgtools/mktools` so, what to do?

Thanks,
/Pedro

**Comment by jperkin** [comment]
Despite the similar name, they are different things.  `mktools` is a package that I started where I was going to write a bunch of utilities in C, and started with `mk-buildlink3-symlinks`, but I didn't get any further.  It may be that myself or others may add things to it in the future, but my focus now is on `mktool`, and I plan to write a `mk-buildlink3-symlinks` command to it too.

So you can continue to use `PKGSRC_USE_MKTOOLS` and that package will be depended upon, and you can set `TOOLS_PLATFORM.mktool` and opt-in to `mktool` replacements as they are added without having an extra build dependency.

Hope that makes sense.

**Comment by 0323pin** [comment]
Sorry, it's bit confusing. I do know these are different tools but, perhaps I wasn't clear.

I would like to migrate from `pkgtools/mktools` to `mktool` and use **only** the later.
Should I leave `PKGSRC_USE_MKTOOLS= yes` in `/etc/mk.conf` or, remove it from the configuration file?

No rush, I'll wait until the hooks are merged.

**Comment by jperkin** [comment]
Yes you can just leave it. If and when I add mksymlink support to mktool then it will be in preference of mktools.

**Comment by 0323pin** [comment]
Thanks!

**Comment by 0323pin** [comment]
> If and when I add mksymlink support to mktool then it will be in preference of mktools.

Looks like this has been added. I will try to migrate at the end of the week, thanks.

> Should I leave PKGSRC_USE_MKTOOLS= yes in /etc/mk.conf or, remove it from the configuration file?
